In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier



In [ ]:
df=pd.read_csv('TitanicDataset.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
df.head()

df.drop(columns = ['PassengerId','Cabin','Name', 'Ticket'], inplace =True)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']), df['Survived'], test_size =0.2, random_state=42)

In [ ]:
df.isnull().sum()
x_train.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [ ]:
print(x_train.head() , y_train.head())

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S 331    0
733    0
382    0
704    0
813    0
Name: Survived, dtype: int64


In [ ]:
#since missing values has to dealt with since they might cause an error in the model prediction system

si_age= SimpleImputer()
si_embarked = SimpleImputer(strategy = 'most_frequent')

x_train_age = si_age.fit_transform(x_train[['Age']])
x_test_age = si_age.transform(x_test[['Age']])

x_train_age = si_embarked.fit_transform(x_train[['Embarked']])
x_test_age = si_embarked.transform(x_test[['Embarked']])


In [ ]:
ohe_sex = OneHotEncoder(sparse_output=False, handle_unknown = 'ignore')
ohe_embarked = OneHotEncoder(sparse_output=False, handle_unknown = 'ignore')

x_train_sex = ohe_sex.fit_transform(x_train[['Sex']])
x_test_sex = ohe_sex.transform(x_test[['Sex']])

x_train_embarked = ohe_embarked.fit_transform(x_train[['Embarked']])
x_test_embarked = ohe_embarked.transform(x_test[['Embarked']])

In [ ]:
x_train_rem = x_train.drop(columns = ['Age', 'Sex', 'Embarked'])
x_test_rem = x_test.drop(columns = ['Age', 'Sex', 'Embarked'])

In [ ]:
print(x_train_rem.head(10))
print(x_test_rem.head(10))

     Pclass  SibSp  Parch      Fare
331       1      0      0   28.5000
733       2      0      0   13.0000
382       3      0      0    7.9250
704       3      1      0    7.8542
813       3      4      2   31.2750
118       1      0      1  247.5208
536       1      0      0   26.5500
361       2      1      0   27.7208
29        3      0      0    7.8958
55        1      0      0   35.5000
     Pclass  SibSp  Parch     Fare
709       3      1      1  15.2458
439       2      0      0  10.5000
840       3      0      0   7.9250
720       2      0      1  33.0000
39        3      1      0  11.2417
290       1      0      0  78.8500
300       3      0      0   7.7500
333       3      2      0  18.0000
208       3      0      0   7.7500
136       1      0      2  26.2833


In [ ]:
x_train_new = np.concatenate((x_train_rem, x_train_age, x_train_sex, x_train_embarked), axis=1)
x_test_new = np.concatenate((x_test_rem, x_test_age, x_test_sex, x_test_embarked), axis=1)

In [ ]:
x_train_new

array([[1.0, 0.0, 0.0, ..., 0.0, 1.0, 0.0],
       [2.0, 0.0, 0.0, ..., 0.0, 1.0, 0.0],
       [3.0, 0.0, 0.0, ..., 0.0, 1.0, 0.0],
       ...,
       [3.0, 2.0, 0.0, ..., 0.0, 1.0, 0.0],
       [1.0, 1.0, 2.0, ..., 0.0, 1.0, 0.0],
       [1.0, 0.0, 1.0, ..., 0.0, 1.0, 0.0]], dtype=object)

In [ ]:
clf = DecisionTreeClassifier()
#y_train = np.array(y_train)
x_train_new = pd.DataFrame(x_train_new)
x_train_new = x_train_new.apply(pd.to_numeric, errors='coerce')


clf.fit(x_train_new, y_train)

DecisionTreeClassifier()

In [ ]:
x_test_new = pd.DataFrame(x_test_new)
x_test_new = x_test_new.apply(pd.to_numeric, errors='coerce')

y_pred = clf.predict(x_test_new)

In [ ]:

from sklearn.metrics import accuracy_score
accuracy = accuracy_score( y_pred,y_test )

accuracy

0.8044692737430168

In [ ]:
import pickle
import os

# Create folder if it doesn't exist
os.makedirs('models', exist_ok=True)

pickle.dump(ohe_sex,open('models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('models/ohe_embarked.pkl','wb'))
pickle.dump(clf,open('models/clf.pkl','wb'))

#Loading Everything Back
#for the User Input

In [ ]:
import pickle
import numpy as np

ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

 # Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male' ,31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

test_input



test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

test_input_embarked = ohe_embarked. transform(test_input[:,-1].reshape(1,1))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [ ]:
test_input_sex

array([[0., 1.]])

In [ ]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))
test_input_embarked

test_input_age = test_input[:,2].reshape(1,1)
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [ ]:
clf.predict(test_input_transformed)

array([0])